### PR TITLE
Fix slack url

### LINKED ISSUE #346: Fix slack message
somehow slack messages are now appearing as: `Create: sideboard deployment master successful.  Application will be available at <https://[object Object]>`

### PR DESCRIPTION
**Pull request by bennett000**
fixes #346

### CODE REVIEW

File: src/aws/aws-constants.js [hunk 1]
```diff
@@ -30,7 +30,8 @@ const EXPORTS = {
   AWS_RETRY_LIMIT: 3,
   AWS_RETRY_MULTIPLIER: 3,
   ALT_TAG: '-alt',
-  CIDR_BLOCK: '10.0.0.0/16'
+  CIDR_BLOCK: '10.0.0.0/16',
+  PR_EXPIRY: 10 * 1000 * 60 * 60
```
Comment (SethDavenport) [inline src/aws/aws-constants.js]: There's some overlap between this PR and #413?

**Comment by SethDavenport** [comment]
:shipit:
